from datetime import datetime
from typing import TYPE_CHECKING, Any

if TYPE_CHECKING:
    from core.session import Session


def generate_report(session: "Session") -> tuple[str, str]:
    """Return the session results as (markdown, plain_text) strings."""
    return _build_markdown(session), _build_plaintext(session)


def _build_markdown(session: "Session") -> str:
    rs = session.result_store
    now = datetime.now().strftime("%Y-%m-%d %H:%M")
    lines: list[str] = [
        "# SecHub Report",
        "",
        "| Field | Value |",
        "|-------|-------|",
        f"| Target | `{session.target}` |",
        f"| Started | {session.created_at[:19]} |",
        f"| Generated | {now} |",
        "",
    ]

    # Phase 1 — Reconnaissance
    p1 = rs.get("phase1", {})
    lines += ["## Phase 1 — Reconnaissance", ""]

    whois = p1.get("whois", {})
    if whois:
        lines += ["### WHOIS", ""]
        for k, v in whois.items():
            display = ", ".join(v) if isinstance(v, list) else v
            lines.append(f"- **{k}:** {display}")
        lines.append("")

    ports = p1.get("ports", [])
    if ports:
        lines += [
            "### Port Scan",
            "",
            "| Port | Protocol | State | Service | Version |",
            "|------|----------|-------|---------|---------|",
        ]
        for p in ports:
            ver = p.get("version") or "-"
            lines.append(
                f"| {p['port']} | {p['protocol']} | {p['state']} | {p['service']} | {ver} |"
            )
        lines.append("")

    if p1.get("os"):
        lines += ["### OS Detection", "", f"- {p1['os']}", ""]

    # Phase 2 — Vulnerability Analysis
    p2 = rs.get("phase2", {})
    lines += ["## Phase 2 — Vulnerability Analysis", ""]

    exploits = p2.get("exploits", [])
    if exploits:
        lines += [
            "### ExploitDB Results (sorted by score)",
            "",
            "| Score | Title | Path |",
            "|-------|-------|------|",
        ]
        for e in exploits[:10]:
            lines.append(f"| {e.get('score', 0)} | {e['title']} | `{e['path']}` |")
        lines.append("")

    cves = p2.get("cves", [])
    if cves:
        lines += [
            "### CVE / CVSS",
            "",
            "| CVE ID | CVSS | Description |",
            "|--------|------|-------------|",
        ]
        for c in cves:
            score = c.get("cvss_score") or "-"
            desc = (c.get("description") or "")[:80]
            lines.append(f"| {c['cve_id']} | {score} | {desc} |")
        lines.append("")

    gobuster = p2.get("gobuster", [])
    if gobuster:
        lines += ["### Web Directories (gobuster)", ""]
        for entry in gobuster[:20]:
            lines.append(f"- `{entry['path']}` — HTTP {entry['status']}")
        lines.append("")

    whatweb = p2.get("whatweb", [])
    if whatweb:
        lines += ["### Web Technologies (whatweb)", ""]
        for entry in whatweb:
            techs = ", ".join(
                f"{t['name']} [{t['version']}]" for t in entry.get("technologies", [])
            )
            lines.append(f"- `{entry['url']}` — {techs}")
        lines.append("")

    # Phase 3 — Exploitation
    p3 = rs.get("phase3", {})
    lines += ["## Phase 3 — Exploitation", ""]

    credentials = p3.get("credentials", [])
    if credentials:
        lines += [
            "### Credentials Found",
            "",
            "| Service | Port | Login | Password |",
            "|---------|------|-------|----------|",
        ]
        for c in credentials:
            lines.append(
                f"| {c.get('service', '-')} | {c.get('port', '-')} "
                f"| {c.get('login', '-')} | {c.get('password', '-')} |"
            )
        lines.append("")

    databases = p3.get("databases", [])
    if databases:
        lines += ["### Databases Found (sqlmap)", ""]
        for db in databases:
            lines.append(f"- `{db}`")
        lines.append("")

    if not credentials and not databases:
        lines += ["_(no exploitation data recorded)_", ""]

    # Phase 4 — Post-Exploitation
    p4 = rs.get("phase4", {})
    lines += ["## Phase 4 — Post-Exploitation", ""]

    sysinfo_raw = p4.get("sysinfo")
    sysinfo_parsed = p4.get("sysinfo_parsed", {})
    if sysinfo_parsed:
        lines += ["### System Info", ""]
        for k, v in sysinfo_parsed.items():
            lines.append(f"- **{k}:** {v}")
        lines.append("")
    elif sysinfo_raw:
        lines += ["### System Info", "", f"```\n{sysinfo_raw}\n```", ""]

    hashes = p4.get("hashes", [])
    if hashes:
        lines += ["### Collected Hashes", ""]
        for h in hashes:
            lines.append(f"- `{h}`")
        lines.append("")

    lines += ["---", f"*Generated by SecHub — {now}*"]
    return "\n".join(lines)


def _build_plaintext(session: "Session") -> str:
    rs = session.result_store
    now = datetime.now().strftime("%Y-%m-%d %H:%M")
    sep = "=" * 60
    thin = "-" * 40
    lines: list[str] = [
        sep, "SecHub Report", sep,
        f"Target    : {session.target}",
        f"Started   : {session.created_at[:19]}",
        f"Generated : {now}",
        "",
    ]

    p1 = rs.get("phase1", {})
    lines += [thin, "Phase 1 — Reconnaissance", thin]
    for port in p1.get("ports", []):
        ver = port.get("version") or ""
        lines.append(f"  {port['port']}/{port['protocol']}  {port['state']}  {port['service']}  {ver}")
    if p1.get("os"):
        lines.append(f"  OS: {p1['os']}")
    lines.append("")

    p2 = rs.get("phase2", {})
    lines += [thin, "Phase 2 — Vulnerability Analysis", thin]
    for e in p2.get("exploits", [])[:10]:
        lines.append(f"  [{e.get('score', 0)}] {e['title']}")
    for c in p2.get("cves", []):
        lines.append(f"  {c['cve_id']}  CVSS:{c.get('cvss_score', '-')}")
    for entry in p2.get("gobuster", [])[:10]:
        lines.append(f"  {entry['path']}  ({entry['status']})")
    lines.append("")

    p3 = rs.get("phase3", {})
    lines += [thin, "Phase 3 — Exploitation", thin]
    for c in p3.get("credentials", []):
        lines.append(f"  CREDENTIAL  {c.get('service')}:{c.get('port')}  {c.get('login')} / {c.get('password')}")
    for db in p3.get("databases", []):
        lines.append(f"  DATABASE  {db}")
    if not p3.get("credentials") and not p3.get("databases"):
        lines.append("  No data recorded.")
    lines.append("")

    p4 = rs.get("phase4", {})
    lines += [thin, "Phase 4 — Post-Exploitation", thin]
    sysinfo_parsed = p4.get("sysinfo_parsed", {})
    if sysinfo_parsed:
        for k, v in sysinfo_parsed.items():
            lines.append(f"  {k}: {v}")
    elif p4.get("sysinfo"):
        lines.append(p4["sysinfo"][:500])
    for h in p4.get("hashes", []):
        lines.append(f"  HASH: {h}")
    lines.append("")

    lines += [sep, f"Generated by SecHub — {now}", sep]
    return "\n".join(lines)
